### PR TITLE
bug(#37 queue and context fields were not set)

### PR DESCRIPTION
**Pull request by worldspawn**
- now set in init method

### CODE REVIEW

**Comment by worldspawn** [comment]
Would it be ok to set these in the constructor?

**Comment by MarkPieszak** [comment]
I believe so, merging and publishing this - let me know if something comes up!
@worldspawn 

Great job 💯 👍 👍

**Comment by MarkPieszak** [comment]
These are set within `.init()`, since sometimes we don't have everything setup right away. 
Is that not working? @worldspawn

**Comment by worldspawn** [comment]
I can't see where that happens - can you link me a line?

**Comment by MarkPieszak** [comment]
Oh my goodness, sorry about that - I was super tired yesterday!
The code I looked at was from what you added 😆 🤣 

Merging this and publishing a new version, sorry about the mix up!!

You rock 🎸

**Pull request merged**
