### PR TITLE
Bump to 2.0.0 with bump to NG4

### PR DESCRIPTION
**Pull request by viperguynaz**
targets es6 - that ok?

### CODE REVIEW

**Comment by MarkPieszak** [comment]
I think we should stick with es5? 
I need to add rollup to handle providing an es2015-module delivery bundle as well.

**Comment by viperguynaz** [comment]
I was getting conflicts with "target": "es5" - I'll keep investigating.

**Comment by viperguynaz** [comment]
@MarkPieszak - reverted to es5

**Comment by MarkPieszak** [comment]
Ahh there it is, TS version is usually the route of all problems I've found out :hatched_chick: lol
Let me push out a new version! @viperguynaz :100:

**Pull request merged**
