### PR TITLE
Optional instrumentationKey in forRoot

### PR DESCRIPTION
**Pull request by jycouet**
Hi, 

I'm doing this small PR because I think it will help people :)

- https://github.com/MarkPieszak/angular-application-insights/issues/24
- https://github.com/MarkPieszak/angular-application-insights/issues/17

Like this, you still get a warning if you didn't configure your Module, but you can set your **instrumentationKey** later.

---
app.module.ts
```js
imports: [
ApplicationInsightsModule.forRoot({
      //instrumentationKey: __env.APPINSIGHTS_INSTRUMENTATIONKEY
      instrumentationKeySetlater: true 
    })
]
```
app.component.ts
```js
constructor(private appInsightsService: AppInsightsService) {
    appInsightsService.config = {
      instrumentationKey: __env.APPINSIGHTS_INSTRUMENTATIONKEY
    }
    appInsightsService.init();
}
```

And like this I can set my __env.APPINSIGHTS_INSTRUMENTATIONKEY depending on my environement, after my angular application is built! :)

I hope you will enjoy.

### CODE REVIEW

**Comment by MarkPieszak** [comment]
This looks great!! Thank you so much for helping out, I didn't get a chance to get to this one yet! @jycouet 

👏 👏 🍻 

I'll merge this in and publish a new version!

There aren't any breaking changes to existing projects right?

**Comment by jycouet** [comment]
Nop, I didn't saw any breaking changes.
//Happy coding only 😆

**Comment by jycouet** [comment]
How can I see when you publish the 📦 ? Or can you write it here?
Thank you @MarkPieszak

**Comment by MarkPieszak** [comment]
Did it right after merging and adding your notes in the readme, I always do a publish() commit and message too. You're all set!

Latest commit a31de75  3 hours ago - publish(2.4): new set InstrumentationKey later feature

**Pull request merged**
