### PR TITLE
Update angular packages to 4.1.1

### PR DESCRIPTION
**Pull request by jycouet**
Angular updated again to new packages version (4.1.1) and your package v2.0.0 is not working with angular 4.1.1.

Issue you add before here: https://github.com/MarkPieszak/angular-application-insights/issues/10 

I updated the package.json to the latest 4.1.1
It's working on my side.

Could you look at this PR and publish it to npm? :)

Thank you

### CODE REVIEW

**Comment by viperguynaz** [comment]
looks good! :shipit:

**Comment by MarkPieszak** [comment]
We don't want **`^`** `4.1.1` for the Angular dependencies?
Also we should keep the package at 2.x, and do `2.1` for those doing ^2.0 for this (otherwise they won't get latest when they npm install or update).

**Comment by jycouet** [comment]
I agree with your version number strategy :)
I updated my PR.

**_Recap table:_**

| angular-application-insights | Angular|
| ------------:|:---------------|
| v1.0.0 | v2.4.0 | 
| v2.0.0 | v4.0.1 |  
| v2.1.0 | v4.1.1 |

**Comment by jycouet** [comment]
Hi @MarkPieszak, 
Could you tell me when you will have time to publish this?

Thank you for the info.

**Comment by MarkPieszak** [comment]
Apologies! I'll merge this in, update to 2.2 (I just merged one that did 2.1) and I'll push to npm. I'll ping you when it's up there.

**Comment by MarkPieszak** [comment]
@jycouet Published version 2.2.0 with these updates! 🍾

**Comment by jycouet** [comment]
Thank you 😃

**Pull request merged**
