### PR TITLE
Added Application Insights SDK

### PR DESCRIPTION
**Pull request by KiselN**
Take a look, please.
I included SDK using this approach
https://github.com/Microsoft/ApplicationInsights-JS/blob/master/README.md#import-as-a-module-and-initialize-dynamically-download-full-application-insights-script-from-cdn
and made several minor changes.

### CODE REVIEW

**Comment by MarkPieszak** [comment]
This looks great!
I was looking at their js-sdk last night actually.

Do users still need to throw in that JS `<script>` in their pages, or does the SDK handle all of this now instead?

**Comment by KiselN** [comment]
No they don't need to include that snippet anymore. I was pleasantly surprised when I found out!

**Comment by johnkattenhorn** [comment]
Hey @MarkPieszak, @KiselN and I work together, thanks again for helping us get started on this, it's nice to give back!

**Comment by MarkPieszak** [comment]
Oh great I had no idea! Glad we're all getting the ball rolling with this one.

Looks like we have a few issues to deal with (if we're going to use that SDK so far)
The SDK is packaging everything in `AMD` so we can't use that, they don't support CommonJS at the moment. (https://github.com/Microsoft/ApplicationInsights-JS/issues/301)

We might need to just abstract out the library itself (https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK.Module/AppInsightsModule.ts) and create a Class that works for us here.

**Comment by johnkattenhorn** [comment]
Did you see the alternative Application Insights library [here](https://github.com/khaines/angular-applicationinsights) in which they seem to have built an implementation without the core library. A lot more work but I'm wondering if they did this because of some of the issues you have already highlighted.

**Pull request merged**
