### PR TITLE
Optional instrumentationKey in forRoot (with correct log)

### PR DESCRIPTION
**Pull request by jycouet**
Sorry I maid a mistake in my previous PR (https://github.com/MarkPieszak/angular-application-insights/pull/29).

It's just a log error, no functional problem.
Can you update it please?

Thank you

### CODE REVIEW

**Comment by MarkPieszak** [comment]
Published as @markpieszak/ng-application-insights@2.4.1 🍺

**Comment by jycouet** [comment]
Thx 👍

**Comment by jycouet** [comment]
Hi @MarkPieszak, 
Sorry it's me again.

On npm, is the dist folder published?
Because it's not sync with `app-insight.service.ts`
So my last correction is not in `app-insight.service.js` 😒 

Could you check this please?
Thank you

**Comment by MarkPieszak** [comment]
Even with 2.4.1? Let me double check

**Comment by jycouet** [comment]
Yep, in 2.4.1

**Comment by jycouet** [comment]
Sorry @MarkPieszak, do you have any news? :)

**Comment by jycouet** [comment]
Hey @MarkPieszak it's me again.
Could you please release the 2.4.2 to have the correct dist folder?

When I install the 2.4.1 I get the latest src/app-insight.service.ts but the old dist folder. I think you just need to build again the dist then deploy.

Thank you for your help

**Comment by MarkPieszak** [comment]
I will right in the morning tomorrow apologies been traveling the past few days didn't have a moment 😔 Just got back home tonight

**Comment by jycouet** [comment]
Hello @MarkPieszak, 
I think that you forgot me ^^. Right? :)

**Comment by MarkPieszak** [comment]
Oh no!!! I forgot sorry I was in Europe for quite a while! So sorry about that :(

Fixed now via 2.4.2! @jycouet 🍻

**Comment by jycouet** [comment]
thx :)

**Pull request merged**
